### ISSUE TITLE
Swift backup target for Snapshot - HasWriteAccess() attempts RemoveItem() too fast

### ISSUE THREAD

**Issue by piersharding** [kubedb/issues#336]
Hi -

When HasWriteAccess() (https://github.com/appscode/stow/blob/master/swift/container.go#L167) is used to determine whether a Swift Container is available as a repository for KubeDB Snapshot backups, the RemoveItem() phase can happen too quickly after the Put() phase leading to an error being generated "Object Not Found" .   This timing issue is more likely to occur when the Swift Object Store uses cross data-centre replication as there is a delay until Object replication is complete (and consistency achieved) before Swift acknowledges the object is available.
Would it be possible to make the HasWriteAccess() test configurable/optional, or remove it all together (as object stores are eventually consistent)?

Thanks,
Piers.

**Comment by piersharding** [comment]
After some further investigation, it is also possible to swallow the RemoveItem() error, as Swift eventual consistency does the 'right thing' and will still register the delete.
The following works:
```
func (c *container) HasWriteAccess() error {
	r := bytes.NewReader([]byte("CheckBucketAccess"))
	item, err := c.Put(".objectstore", r, r.Size(), nil)
	if err != nil {
		return err
	}
	if err := c.RemoveItem(item.ID()); err != nil {
		// return err
        log.Warningln("Swift HasWriteAccess() ignoring error - probably delayed replication: %v", item.ID())
	}
	return nil
}
```

**Comment by tamalsaha** [comment]
Obsolete. Use https://stash.run
