### ISSUE TITLE
Deleting snapshot pod causes backup to stall

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/issues#354]
https://kubernetes.slack.com/archives/C8149MREV/p1544260937122700

We should handle this gracefully.

**Comment by the-redback** [comment]
Kubernetes recovers the snapshot `pod` deletion. But, in the case of snapshot `job` deletion, the backup becomes stall. We will handle this reconcile once we integrate restic for snapshot. 

Meanwhile, for workaround, delete that stall snapshot.

**Comment by tamalsaha** [comment]
Obsolete.
