### ISSUE TITLE
Design pre-configured plans for various databases

### ISSUE THREAD

**Issue by botzill** [kubedb/issues#439]
Hi.

I'm interested if you plan to create helm charts for specific database? At the moment we are using terragrunt to deploy our infrastructure and we can't pass raw yaml file to k8s. Having helm charts for all the databass would be really nice to test and install it. 

Thx !

**Comment by tamalsaha** [comment]
We have heard this feature request before. But the part is not clear to me is:

A chart like that will probably just have variable for every field in the CRD. How useful is that?

**Comment by botzill** [comment]
Well, having a single database helm chart will be really useful and easy to install(with some default settings should work out of the box). But most useful for me is that I can easily install it using `terraform`, as said I have no way to pass raw yaml file in `terraform` so, I have to create helm charts. 

Using helm chart we can easily enable/disable specific features like backup, statistics and other.

**Comment by tamalsaha** [comment]
I am looking into this with the help of SUSE folks as part of https://github.com/appscode/service-broker/issues/48 . We are going to provide Charts that configure various CRD components for a CRD with a number of predefined values file for each type of resource.

**Comment by tamalsaha** [comment]
We are going to create kustomize bundles in https://github.com/kubedb/profiles repo . Here are some CRDs we plan to include.

<table>
  <tr>
   <td><strong>Functionality</strong>
   </td>
   <td><strong>Name of CRD</strong>
   </td>
  </tr>
  <tr>
   <td>Database CRD
   </td>
   <td><code>Postgres / Elasticsearch</code>
   </td>
  </tr>
  <tr>
   <td>Backup using Stash
   </td>
   <td><code>BackupConfiguration</code>
<p>
<code>Repository</code>
   </td>
  </tr>
  <tr>
   <td>Monitoring via Prometheus 
<p>
+
<p>
Dashboards using Grafana
   </td>
   <td><code>ServiceMonitor (prometheus-operator)</code>
<p>
<code>PrometheusRule (prometheus-operator)</code>
<p>
<code>DashboardTemplate (grafana-operator)</code>
<p>
<code>Dashboard (grafana-operator)</code>
   </td>
  </tr>
  <tr>
   <td>User Management using KubeVault
   </td>
   <td><code>VaultServer</code>
<p>
<code>PostgresRole</code>
<p>
<code>MongoDBRole</code>
<p>
<code>MySQRole</code>
   </td>
  </tr>
  <tr>
   <td>Certificate Management using jetstack/cert-manager
   </td>
   <td><code>Issuer</code>
<p>
<code>ClusterIssuer</code>
   </td>
  </tr>
  <tr>
   <td>Security
   </td>
   <td><code>NetworkPolicy</code>
   </td>
  </tr>
  <tr>
   <td>Ingress
   </td>
   <td><code>Ingress</code>
   </td>
  </tr>
  <tr>
   <td>Policy Management using 
<p>
<a href="https://github.com/open-policy-agent/gatekeeper">Open Policy Agent</a>
<p>
(needs further research)
   </td>
   <td>
   </td>
  </tr>
</table>

xref: https://github.com/kmodules/monitoring-agent-api/issues/25

cc: @apu1111

**Comment by tamalsaha** [comment]
This work is done using kustomize here: https://github.com/kubedb/profiles

**Comment by tamalsaha** [comment]
We have decided to focus on charts. You can find it here: https://github.com/kubedb/profile-charts
