### ISSUE TITLE
Fix UpsertDatabaseAnnotation() function 

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/issues#549]
**Current implementation:**

```go
func (c *Controller) UpsertDatabaseAnnotation(meta metav1.ObjectMeta, annotation map[string]string) error {
	postgres, err := c.ExtClient.KubedbV1alpha1().Postgreses(meta.Namespace).Get(meta.Name, metav1.GetOptions{})
	if err != nil {
		return err
	}

	_, _, err = util.PatchPostgres(c.ExtClient.KubedbV1alpha1(), postgres, func(in *api.Postgres) *api.Postgres {
		in.Annotations = core_util.UpsertMap(postgres.Annotations, annotation)
		return in
	})
	return err
}
```

**Problem:**

Go Map is pointer type. Hence, original value of `postgres.Annotations` are get changed in this line:

```go
in.Annotations = core_util.UpsertMap(postgres.Annotations, annotation)
```

This cause results in skip patching the original `Postgres` crd as `cur` and `mod` becomes same.

**Fix:**

Change to
```go
in.Annotations = core_util.UpsertMap(in.Annotations, annotation)
```

**Task List:**

- [x] PostgreSQL
- [x] MongoDB
- [x] Elasticsearch
- [x] MySQL
- [x] Etcd
- [x] MariaDB
- [x] Percona

Xref: https://github.com/kubedb/postgres/pull/283

**Comment by Freyert** [comment]
@hossainemruz can this be closed? You've checked all the boxes.
