### ISSUE TITLE
Pass stash.appscode.com/backup-blueprint annotations to AppBindings

### ISSUE THREAD

**Issue by zarbis** [kubedb/issues#669]
Currently `BackupBlueprint` watches for `stash.appscode.com/backup-blueprint` labels on `AppBinding`. Since `AppBinding` is created in runtime after submitting `MongoDB` (or any other database resource), application owner is required to live-patch `AppBinding` via `kubectl annotate`.

This breaks declarative nature of K8s and denies application owner ability to opt-in to auto-backup feature by adding this annotation to `MongoDB` definition in Git repository. I see two possible solutions, add annotation to database resource and:

1. Either watch for annotation directly on `MongoDB` resource, not on `AppBinding`
2. Or pass annotations from `MongoDB` resource to `AppBinding` and keep watching them

**Comment by tamalsaha** [comment]
We are passing annotations from CRD to AppBinding in master. This will be available in the next release.
