### ISSUE TITLE
Database CRD should allow passing a stash backup-blueprint name

### ISSUE THREAD

**Issue by tlvenn** [kubedb/issues#675]
As discussed over Slack, we are using Kubedb with Stash and in order to leverage a blueprint, one has to annotate the created `AppBinding`. We leverage Terraform for our infra and having to annotate an existing resource create a lot of frictions.

Could we extend the database CRDs so the spec could have an optional `stash-backup-blueprint` which would be used to automatically annotate the managed `AppBinding` ?

This would solve #669

**Comment by tamalsaha** [comment]
We are passing annotations from CRD to AppBinding in master. This will be available in the next release.
