### ISSUE TITLE
PodDisruptionPolicy MaxUnavailable on statefulsets can be 0

### ISSUE THREAD

**Issue by andersosthus** [kubedb/issues#713]
In https://github.com/kubedb/apimachinery/blob/518ce3c461bd4f54863192f354219dced990c45f/pkg/controller/lib.go#L148 `MaxUnavailable` is set to `floor((Replicas - 1) / 2)`. For StatefulSets with 1 or 2 replicas, this results in `MaxUnavailable` being set to 0.

This has the unfortunate effect of causing `kubectl drain` to block, since `kubectl drain` respects `MaxUnavailable`.

I propose changing the `MaxUnavailable` resolution to `math.Max(1, math.Floor((float64(*sts.Spec.Replicas) - 1.0) / 2.0))`. This will ensure that you'll always get at least `1` as `MaxUnavailable`. For `StatefulSets` with 3+ replicas, everything will be as before, but for 1-2 replicas, you'll end up with 1 `MaxUnavailable`.

I'll submit a PR to apimachinery with the change I've outlined above.

**Comment by tamalsaha** [comment]
Fixed in https://github.com/kubedb/apimachinery/pull/498
