### ISSUE TITLE
Use Helm 3 `crds` directory to install CRDs

### ISSUE THREAD

**Issue by jwietelmann** [kubedb/issues#718]
https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/

> With the arrival of Helm 3, we removed the old `crd-install` hooks for a more simple methodology. There is now a special directory called `crds` that you can create in your chart to hold your CRDs. These CRDs are not templated, but will be installed by default when running a helm install for the chart. If the CRD already exists, it will be skipped with a warning. If you wish to skip the CRD installation step, you can pass the `--skip-crds` flag.

This would make `kubedb` much easier to install via a `HelmRelease` for `helm-operator`, eliminating a bunch of race conditions that seem to cause things to get jammed up.

**Comment by tamalsaha** [comment]
This can't be done due to https://github.com/helm/helm/issues/7083#issuecomment-573316508 . Thanks for bringing up this issue. We will revisit this if things change on Helm side.
