### ISSUE TITLE
Fix helm deployment of kubedb on ArgoCD (and --wait)

### ISSUE THREAD

**Issue by MrFreezeex** [kubedb/issues#741]
As ArgoCD convert Helm hooks to ArgoCD hooks It acts exactly like a `--wait`, which is broken like reported in https://github.com/kubedb/issues/issues/522.

We want to deploy kubedb using a GitOps flow with ArgoCD and It will ease installation of kubedb on some environments... Can someone take a look at my small PR on the helm chart (https://github.com/kubedb/installer/pull/57) to fix this issue :) ?

**Comment by tamalsaha** [comment]
Fixed by https://github.com/kubedb/installer/pull/57
